# permissions for end users to edit previewenvironmentmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: previewenvironmentmanager-editor-role
rules:
- apiGroups:
  - preview.gitops.phoban.io
  resources:
  - previewenvironmentmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - preview.gitops.phoban.io
  resources:
  - previewenvironmentmanagers/status
  verbs:
  - get
