# permissions for end users to edit previewenvironmentdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: previewenvironmentdefinition-editor-role
rules:
- apiGroups:
  - preview.gitops.phoban.io
  resources:
  - previewenvironmentdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - preview.gitops.phoban.io
  resources:
  - previewenvironmentdefinitions/status
  verbs:
  - get
