# permissions for end users to view previewenvironmentmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: previewenvironmentmanager-viewer-role
rules:
- apiGroups:
  - preview.gitops.phoban.io
  resources:
  - previewenvironmentmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - preview.gitops.phoban.io
  resources:
  - previewenvironmentmanagers/status
  verbs:
  - get
