# permissions for end users to edit previewenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: previewenvironment-editor-role
rules:
- apiGroups:
  - preview.gitops.phoban.io
  resources:
  - previewenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - preview.gitops.phoban.io
  resources:
  - previewenvironments/status
  verbs:
  - get
