---
apiVersion: preview.gitops.phoban.io/v1alpha1
kind: PreviewEnvironmentManager
metadata:
  name: demo-manager
  namespace: preview-env-controller-system
spec:
  interval: 5m
  limit: 2
  # the repository to watch for matching branches
  watch:
    url: https://github.com/phoban01/sample-app
    ref:
      branch: "main"
    credentialsRef:
      name: gh-token
  strategy:
    type: Branch
    # empty rules matches all
    rules:
      # branch
      match: '^feature-.*'
      # pull-request
      # labels:
        # - 'deploy'
      # draft: false
  template:
    # setting this will also set target namespace on the
    # kustomization (currentl sets target but should override and allow for target
    # to be set here)
    prefix: pr-env-
    # interval will be passed to both any template
    # resources created
    createNamespace: true
    kustomizationSpec:
      interval: 1m
      path: './preview-template'
      prune: true
    # can use sourceSpec to point at a different repo
    sourceSpec:
      interval: 1m
