---
apiVersion: preview.gitops.phoban.io/v1alpha1
kind: PreviewEnvironmentManager
metadata:
  name: demo-manager
  namespace: preview-env-controller-system
spec:
  interval: 1m
  limit: 2
  # the repository to watch for matching branches
  watch:
    url: https://github.com/phoban01/sample-app
    ref:
      branch: "main"
    credentialsRef:
      name: gh-token
  rules:
    matchBranch: '^feature-.*'
  template:
    prefix: pr-env-
    kustomizationSpec:
      path: './preview-template'
      interval: 1m
      prune: true
    sourceSpec:
      interval: 1m
